Repository system76/docs, pull requests merged in 2020-08, with the labels that each got.

#424 Replace globs with apt patterns
  _articles/add-a-printer-pop.md
  _articles/add-a-printer-ubuntu.md
  _articles/login-loop-pop.md
  _articles/login-loop-ubuntu.md
Labels: Priority: Low, Status: In Progress

#415 Update quickstart for the Thelio R2
  _articles/desktop-quickstart.md
  images/desktop-quickstart/thelio-r2_ports-diagram_back.png
Labels: Priority: Medium, Status: In Progress

#434 add OpenCL option when installing the driver and rebooting
  _articles/install-davinci-resolve.md
Labels: Priority: Low

#446 add steps to create Window install media
  _articles/dual-booting.md
  images/dual-booting/woeusb.png
Labels: Priority: Low
