Repository system76/docs, pull requests merged in 2021-12, with the labels that each got.

#848 Add WD19TBS to docking-station.md
  content/docking-station.md
Labels: Status: In Progress

#851 Pop basics update
  .markdownlint.json
  content/pop-basics.md
  static/images/pop-basics/21-10-apps-menu.png
  static/images/pop-basics/21-10-new-apps-search.png
  static/images/pop-basics/app-menu-search-21-04.png
  static/images/pop-basics/application-menu-21-04.png
  static/images/pop-basics/cosmic-desktop.png
  static/images/pop-basics/in-app-menu.png
  static/images/pop-basics/pop-workspaces.png
  static/images/pop-basics/top-right-menu.png
  static/images/pop-basics/workspaces.png
Labels: Priority: High, Status: In Progress

#819 Update pop upgrade article
  content/pop-incomplete-upgrade.md
  content/upgrade-pop.md
Labels: Priority: High, Status: In Progress

#865 Update upgrade-pop.md
  content/upgrade-pop.md
Labels: Priority: High
