Repository system76/docs, pull requests merged in 2022-03, with the labels that each got.

#945 Updates for 21.10
  content/enable-hibernation.md
Labels: Priority: Medium, Status: In Progress

#931 Kernelstub
  content/kernelstub.md
Labels: Status: In Progress

#958 Created generic virtualization article
  .gitignore
  content/virtualization.md
  static/images/gnome-boxes/boxes-create-1.png
  static/images/gnome-boxes/boxes-create-2.png
  static/images/gnome-boxes/boxes-create-3.png
  static/images/gnome-boxes/boxes-create-4.png
  static/images/gnome-boxes/boxes-empty.png
  static/images/gnome-boxes/boxes-folder-shares.png
  static/images/gnome-boxes/boxes-full.png
  static/images/gnome-boxes/boxes-snapshots.png
  static/images/gnome-boxes/boxes-vm-access-folder-share.png
  static/images/gnome-boxes/boxes-vm-folder-share-mounted.png
  static/images/gnome-boxes/boxes-vm-install.png
  static/images/gnome-boxes/boxes-vmprefs-usb.png
  static/images/gnome-boxes/boxes-windows-expressinst.png
Labels: Priority: High, Status: In Progress
